### ISSUE TITLE
NoCode error on testmerging (with merge conflict?)

### ISSUE THREAD

**Issue by TiviPlus** [tgstation/tgstation-server-control-panel#135]
reset to local origin selected -> add conflicting pr -> NoCode

```
LibGit2Sharp.InvalidSpecificationException: failed to parse revision specifier - Invalid pattern '(no branch)'
   at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
   at LibGit2Sharp.Core.Proxy.git_revparse_ext(RepositoryHandle repo, String objectish)
   at LibGit2Sharp.Repository.RevParse(String revision, Reference& reference, GitObject& obj)
   at LibGit2Sharp.Commands.Checkout(IRepository repository, String committishOrBranchSpec, CheckoutOptions options)
   at Tgstation.Server.Host.Components.Repository.LibGit2Commands.Checkout(IRepository libGit2Repo, CheckoutOptions checkoutOptions, String commitish) in /home/runner/work/tgstation-server/tgstation-server/src/Tgstation.Server.Host/Components/Repository/LibGit2Commands.cs:line 13
   at Tgstation.Server.Host.Components.Repository.Repository.<RawCheckout>g__RunCheckout|44_0(<>c__DisplayClass44_0& ) in /home/runner/work/tgstation-server/tgstation-server/src/Tgstation.Server.Host/Components/Repository/Repository.cs:line 855
   at Tgstation.Server.Host.Components.Repository.Repository.RawCheckout(String committish, JobProgressReporter progressReporter, CancellationToken cancellationToken) in /home/runner/work/tgstation-server/tgstation-server/src/Tgstation.Server.Host/Components/Repository/Repository.cs:line 862
   at Tgstation.Server.Host.Components.Repository.Repository.<>c__DisplayClass32_0.<CheckoutObject>b__0() in /home/runner/work/tgstation-server/tgstation-server/src/Tgstation.Server.Host/Components/Repository/Repository.cs:line 385
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Tgstation.Server.Host.Components.Repository.Repository.CheckoutObject(String committish, String username, String password, Boolean updateSubmodules, JobProgressReporter progressReporter, CancellationToken cancellationToken) in /home/runner/work/tgstation-server/tgstation-server/src/Tgstation.Server.Host/Components/Repository/Repository.cs:line 381
   at Tgstation.Server.Host.Components.Repository.RepositoryUpdateService.RepositoryUpdateJob(IInstanceCore instance, IDatabaseContextFactory databaseContextFactory, Job job, JobProgressReporter progressReporter, CancellationToken cancellationToken) in /home/runner/work/tgstation-server/tgstation-server/src/Tgstation.Server.Host/Components/Repository/RepositoryUpdateService.cs:line 563
   at Tgstation.Server.Host.Jobs.JobManager.RunJob(Job job, JobEntrypoint operation, CancellationToken cancellationToken) in /home/runner/work/tgstation-server/tgstation-server/src/Tgstation.Server.Host/Jobs/JobManager.cs:line 328
```

**Comment by TiviPlus** [comment]
Related to https://github.com/tgstation/tgstation-server-webpanel/issues/134 in that the only difference is wether "Update to Remote" or "reset to local origin" was selected
