### ISSUE TITLE
job list does not update status of ongoing or complete jobs, reports "Lost connection to the SignalR Hub"

### ISSUE THREAD

**Issue by hry-gh** [tgstation/tgstation-server-control-panel#159]
starting in tgs 5.17 and continuing to 5.18.0, present in webpanel version 4.26.0 to 5.1.0, the webpanel constantly reports "Lost connection to the SignalR Hub". in addition, jobs that are started do appear, but do not correctly update their status or disappear once completed

```
Webpanel Version: v5.1.0
Webpanel Mode: GITHUB
API Version: 9.14.0

Error Code: error.bad_hub_connection
Error Description: Error: No Connection with that ID: Status code '404'

Additional Information:
{"addon":{"jsError":{"statusCode":404}},"config":{"githubtoken":{"id":"config.githubtoken","type":"pwd","value":""},"apipath":{"id":"config.apipath","type":"str","site_local":true,"value":"https://tgs.cm-ss13.com/"},"jobpollinactive":{"id":"config.jobpollinactive","type":"num","value":15},"jobpollactive":{"id":"config.jobpollactive","type":"num","value":5},"jobswidgetdisplay":{"id":"config.jobswidgetdisplay","type":"enum","possibleValues":{"ALWAYS":"always","AUTO":"auto","NEVER":"never"},"value":"auto"},"instanceprobetimer":{"id":"config.instanceprobetimer","type":"num","value":60},"itemsperpage":{"id":"config.itemsperpage","type":"num","value":25,"min":1,"max":100},"instanceeditsidebar":{"id":"config.instanceeditsidebar","type":"enum","possibleValues":{"AUTO":"auto","COLLAPSE":"collapse","EXPAND":"expand"},"value":"auto"},"showjson":{"id":"config.showjson","type":"bool","value":true},"manualpr":{"id":"config.manualpr","type":"bool","value":true},"restjobs2":{"id":"config.restjobs2","type":"bool","value":false}},"stack":"Error\\n    at new d (https://tgstation.github.io/tgstation-server-webpanel/api/9.14.0/607.da3304c987874cca84eb.bundle.js:1:50428)\\n    at https://tgstation.github.io/tgstation-server-webpanel/api/9.14.0/607.da3304c987874cca84eb.bundle.js:1:57445"}
```

**Comment by Cyberboss** [comment]
Are you running TGS behind a reverse proxy? Make sure it allows server sent events (SSE).

**Comment by Cyberboss** [comment]
To be clear, you are on TGS 5.18 and webpanel 5.1.0?

**Comment by hry-gh** [comment]
> Are you running TGS behind a reverse proxy? Make sure it allows server sent events (SSE).

yep - it was entirely this, adding the directives:
```nginx
proxy_buffering off;
proxy_cache off;
```
to our nginx location sorted it out, thank you!

**Comment by Cyberboss** [comment]
@harryob if you get a chance to confirm a theory of mine, undo the changes you did to nginx and update to 5.18.1. I think I fixed it on the TGS side so that it bypasses it.

**Comment by hry-gh** [comment]
> @harryob if you get a chance to confirm a theory of mine, undo the changes you did to nginx and update to 5.18.1. I think I fixed it on the TGS side so that it bypasses it.

yeah, 5.18.1 works without the additional nginx directives, thank you!
