### ISSUE TITLE
Completed jobs keep polling

### ISSUE THREAD

**Issue by Cyberboss** [tgstation/tgstation-server-control-panel#22]
![image](https://user-images.githubusercontent.com/8171642/103464566-bf519400-4d02-11eb-8d23-7320314be81c.png)

```
[18:57:23] dbg: Tgstation.Server.Host.Controllers.DreamDaemonController (Instance:1|Job:|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:)
    Starting API request: Version: 8.1.1. User-Agent: Tgstation.Server.ControlPanel/1.14.0.0
[18:57:23] dbg: Tgstation.Server.Host.Jobs.JobManager (Instance:1|Job:|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Registering job 5: Launch DreamDaemon...
[18:57:23] vrb: Tgstation.Server.Host.Jobs.JobManager (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Starting job...
[18:57:23] vrb: Tgstation.Server.Host.Components.Watchdog.PosixWatchdog (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Begin LaunchImplNoLock
[18:57:23] vrb: Tgstation.Server.Host.Components.Chat.ChatManager (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Chat send "WD: Launching..." to channels:
[18:57:23] vrb: Tgstation.Server.Host.Components.StaticFiles.Configuration (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    No event scripts starting with "WatchdogLaunch" detected
[18:57:23] vrb: Tgstation.Server.Host.Components.Deployment.DmbFactory (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Compile job 1 lock count now: 2
[18:57:23] vrb: Tgstation.Server.Host.Components.Watchdog.PosixWatchdog (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Initializing controller with CompileJob 1...
[18:57:23] vrb: Tgstation.Server.Host.Components.Deployment.Remote.RemoteDeploymentManagerFactory (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Creating remote deployment manager for remote git provider GitHub...
[18:57:23] vrb: Tgstation.Server.Host.Components.Deployment.Remote.GitHubRemoteDeploymentManager (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Not updating deployment as it is missing a repo ID or deployment ID.
[18:57:23] vrb: Tgstation.Server.Host.Components.Watchdog.PosixWatchdog (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Prep for server launch. pendingSwappable is not available
[18:57:23] vrb: Tgstation.Server.Host.Components.Deployment.DmbFactory (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Loading compile job 1...
[18:57:23] vrb: Tgstation.Server.Host.Components.Deployment.DmbFactory (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Compile job 1 lock count now: 3
[18:57:23] vrb: Tgstation.Server.Host.Components.Watchdog.PosixWatchdog (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Hard linking compile job...
[18:57:23] vrb: Tgstation.Server.Host.Components.Session.SessionControllerFactory (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Begin session launch...
[18:57:23] vrb: Tgstation.Server.Host.Components.Chat.ChatTrackingContext (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Activated
[18:57:23] vrb: Tgstation.Server.Host.Components.Byond.ByondManager (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Creating ByondExecutableLock lock for version 513.1536
[18:57:23] dbg: Tgstation.Server.Host.Components.Session.SessionControllerFactory (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Launching session with CompileJob 1...
[18:57:23] vrb: Tgstation.Server.Host.Components.Session.SessionControllerFactory (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Bind test: 1337
[18:57:23] dbg: Tgstation.Server.Host.System.ProcessExecutor (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Launching process in /tgs4_instances/tgstation/Game/Live: /tgs4_instances/tgstation/Byond/513.1536/byond/bin/DreamDaemon.sh tgstation.dmb -port 1337 -ports 1-65535 -close -trusted -public -public -params "server_service_version=5.2.10&tgs_port=5000&tgs_key=MI312NdnPPda7n6C7A7IpCxd2DZs%2b%2fJw3VUSjZpS"
[18:57:23] vrb: Tgstation.Server.Host.System.Process (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Created process ID: 6392
[18:57:23] vrb: Tgstation.Server.Host.Components.InstanceManager (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Registered bridge handler: MI312NdnPPda7n6C7A7IpCxd2DZs+/Jw3VUSjZpS
[18:57:23] vrb: Tgstation.Server.Host.Components.Session.SessionController (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Waiting for LaunchResult based on initial bridge request with a timeout of 60s...
[18:57:23] dbg: Tgstation.Server.Host.Components.Session.SessionController (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Created session controller. CommsKey: MI312NdnPPda7n6C7A7IpCxd2DZs+/Jw3VUSjZpS, Port: 1337
[18:57:23] dbg: Tgstation.Server.Host.System.Process (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Error on WaitForInputIdle()!
System.InvalidOperationException: WaitForInputIdle failed.  This could be because the process does not have a graphical interface.
   at System.Diagnostics.Process.WaitForInputIdleCore(Int32 milliseconds)
   at System.Diagnostics.Process.WaitForInputIdle()
   at Tgstation.Server.Host.System.Process.<>c__DisplayClass16_0.<.ctor>b__0() in /repo/src/Tgstation.Server.Host/System/Process.cs:line 93
[18:57:23] vrb: Tgstation.Server.Host.System.Process (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Set PID 6392 to above normal priority
[18:57:23] dbg: Tgstation.Server.Host.Controllers.JobController (Instance:1|Job:|Request:GET /Job|User:1|Monitor:|Bridge:|Chat:|IR:)
    Starting API request: Version: 8.1.1. User-Agent: tgstation-server-control-panel/2.0.1
[18:57:23] dbg: Tgstation.Server.Host.Controllers.JobController (Instance:1|Job:|Request:GET /Job/4|User:1|Monitor:|Bridge:|Chat:|IR:)
    Starting API request: Version: 8.1.1. User-Agent: tgstation-server-control-panel/2.0.1
[18:57:23] dbg: Tgstation.Server.Host.Controllers.JobController (Instance:1|Job:|Request:GET /Job/4|User:1|Monitor:|Bridge:|Chat:|IR:)
    Starting API request: Version: 8.1.1. User-Agent: tgstation-server-control-panel/2.0.1
[18:57:23] dbg: Tgstation.Server.Host.Controllers.JobController (Instance:1|Job:|Request:GET /Job/5|User:1|Monitor:|Bridge:|Chat:|IR:)
    Starting API request: Version: 8.1.1. User-Agent: tgstation-server-control-panel/2.0.1
[18:57:28] dbg: Tgstation.Server.Host.Controllers.JobController (Instance:1|Job:|Request:GET /Job|User:1|Monitor:|Bridge:|Chat:|IR:)
    Starting API request: Version: 8.1.1. User-Agent: tgstation-server-control-panel/2.0.1
[18:57:28] dbg: Tgstation.Server.Host.Controllers.JobController (Instance:1|Job:|Request:GET /Job/4|User:1|Monitor:|Bridge:|Chat:|IR:)
    Starting API request: Version: 8.1.1. User-Agent: tgstation-server-control-panel/2.0.1
[18:57:28] dbg: Tgstation.Server.Host.Controllers.JobController (Instance:1|Job:|Request:GET /Job/4|User:1|Monitor:|Bridge:|Chat:|IR:)
    Starting API request: Version: 8.1.1. User-Agent: tgstation-server-control-panel/2.0.1
[18:57:28] dbg: Tgstation.Server.Host.Controllers.JobController (Instance:1|Job:|Request:GET /Job/5|User:1|Monitor:|Bridge:|Chat:|IR:)
    Starting API request: Version: 8.1.1. User-Agent: tgstation-server-control-panel/2.0.1
[18:57:33] dbg: Tgstation.Server.Host.Controllers.JobController (Instance:1|Job:|Request:GET /Job|User:1|Monitor:|Bridge:|Chat:|IR:)
    Starting API request: Version: 8.1.1. User-Agent: tgstation-server-control-panel/2.0.1
[18:57:33] dbg: Tgstation.Server.Host.Controllers.JobController (Instance:1|Job:|Request:GET /Job/4|User:1|Monitor:|Bridge:|Chat:|IR:)
    Starting API request: Version: 8.1.1. User-Agent: tgstation-server-control-panel/2.0.1
[18:57:33] dbg: Tgstation.Server.Host.Controllers.JobController (Instance:1|Job:|Request:GET /Job/4|User:1|Monitor:|Bridge:|Chat:|IR:)
    Starting API request: Version: 8.1.1. User-Agent: tgstation-server-control-panel/2.0.1
[18:57:33] dbg: Tgstation.Server.Host.Controllers.JobController (Instance:1|Job:|Request:GET /Job/5|User:1|Monitor:|Bridge:|Chat:|IR:)
    Starting API request: Version: 8.1.1. User-Agent: tgstation-server-control-panel/2.0.1
[18:57:34] dbg: Tgstation.Server.Host.Controllers.JobController (Instance:1|Job:|Request:GET /Job/5|User:1|Monitor:|Bridge:|Chat:|IR:)
    Starting API request: Version: 8.1.1. User-Agent: Tgstation.Server.ControlPanel/1.14.0.0
[18:57:37] vrb: Tgstation.Server.Host.Controllers.BridgeController (Instance:|Job:|Request:|User:|Monitor:|Bridge:2|Chat:|IR:)
    Bridge Request: {"minimumSecurityLevel":0,"version":"5.2.9","customCommands":[{"name":"status","helpText":"Gets the admincount, playercount, gamemode, and true game mode of the server","adminOnly":1},{"name":"check","helpText":"Gets the playercount, gamemode, and address of the server","adminOnly":0},{"name":"ahelp","helpText":"<ckey|ticket #> <message|ticket <close|resolve|icissue|reject|reopen <ticket #>|list>>","adminOnly":1},{"name":"namecheck","helpText":"Returns info on the specified target","adminOnly":1},{"name":"adminwho","helpText":"Lists administrators currently on the server","adminOnly":1},{"name":"endnotify","helpText":"Pings the invoker when the round ends","adminOnly":1},{"name":"sdql","helpText":"Runs an SDQL query","adminOnly":1},{"name":"reload_admins","helpText":"Forces the server to reload admins.","adminOnly":1},{"name":"notify","helpText":"Pings the invoker when the round ends","adminOnly":0}],"commandType":1,"accessIdentifier":"MI312NdnPPda7n6C7A7IpCxd2DZs+/Jw3VUSjZpS"}
[18:57:37] vrb: Tgstation.Server.Host.Components.Session.SessionController (Instance:1|Job:|Request:|User:|Monitor:|Bridge:2|Chat:|IR:)
    Handling bridge request...
[18:57:37] vrb: Tgstation.Server.Host.Components.Session.SessionController (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Launch result: Exit Code: , Time 14267.1806ms
[18:57:38] vrb: Tgstation.Server.Host.Components.Watchdog.PosixWatchdog (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Unhardlinking compile job...
[18:57:39] dbg: Tgstation.Server.Host.Controllers.JobController (Instance:1|Job:|Request:GET /Job|User:1|Monitor:|Bridge:|Chat:|IR:)
    Starting API request: Version: 8.1.1. User-Agent: tgstation-server-control-panel/2.0.1
[18:57:39] dbg: Tgstation.Server.Host.Controllers.JobController (Instance:1|Job:|Request:GET /Job/4|User:1|Monitor:|Bridge:|Chat:|IR:)
    Starting API request: Version: 8.1.1. User-Agent: tgstation-server-control-panel/2.0.1
[18:57:39] dbg: Tgstation.Server.Host.Controllers.JobController (Instance:1|Job:|Request:GET /Job/5|User:1|Monitor:|Bridge:|Chat:|IR:)
    Starting API request: Version: 8.1.1. User-Agent: tgstation-server-control-panel/2.0.1
[18:57:39] vrb: Tgstation.Server.Host.System.Process (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Suspended PID 6392
[18:57:39] vrb: Tgstation.Server.Host.Components.Session.SessionController (Instance:1|Job:|Request:|User:|Monitor:|Bridge:2|Chat:|IR:)
    ApiValidationStatus set to RequiresTrusted
[18:57:39] vrb: Tgstation.Server.Host.Components.Chat.ChatTrackingContext (Instance:1|Job:|Request:|User:|Monitor:|Bridge:2|Chat:|IR:)
    Custom commands set.
[18:57:39] vrb: Tgstation.Server.Host.Components.Watchdog.PosixWatchdog (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Symlinking compile job...
[18:57:39] vrb: Tgstation.Server.Host.Controllers.BridgeController (Instance:|Job:|Request:|User:|Monitor:|Bridge:2|Chat:|IR:)
    Bridge Response: {"runtimeInformation":{"serverVersion":"4.7.0","serverPort":5000,"instanceName":"tgstation","revision":{"commitSha":"1dcd9b4438539118938724081e6b51aeb9e03ac1","originCommitSha":"1dcd9b4438539118938724081e6b51aeb9e03ac1"},"securityLevel":0,"testMerges":[],"channels":[]}}
[18:57:40] vrb: Tgstation.Server.Host.System.Process (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Resumed PID 6392
[18:57:40] inf: Tgstation.Server.Host.Components.Watchdog.PosixWatchdog (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Controller(s) initialized successfully
[18:57:40] vrb: Tgstation.Server.Host.Components.Watchdog.PosixWatchdog (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Entered MonitorLifetimes
[18:57:40] vrb: Tgstation.Server.Host.Components.Watchdog.PosixWatchdog (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Status set to Online
[18:57:40] vrb: Tgstation.Server.Host.Components.Watchdog.PosixWatchdog (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:1|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Iteration 1 of monitor loop
[18:57:40] dbg: Tgstation.Server.Host.Jobs.JobManager (Instance:1|Job:5|Request:PUT /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:27b19db2-f5d5-4aa4-b2fe-24624049691a)
    Job 5 completed!
[18:57:40] dbg: Tgstation.Server.Host.Controllers.JobController (Instance:1|Job:|Request:GET /Job/4|User:1|Monitor:|Bridge:|Chat:|IR:)
    Starting API request: Version: 8.1.1. User-Agent: tgstation-server-control-panel/2.0.1
[18:57:44] dbg: Tgstation.Server.Host.Controllers.JobController (Instance:1|Job:|Request:GET /Job/5|User:1|Monitor:|Bridge:|Chat:|IR:)
    Starting API request: Version: 8.1.1. User-Agent: Tgstation.Server.ControlPanel/1.14.0.0
[18:57:44] dbg: Tgstation.Server.Host.Controllers.DreamDaemonController (Instance:1|Job:|Request:GET /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:)
    Starting API request: Version: 8.1.1. User-Agent: Tgstation.Server.ControlPanel/1.14.0.0
[18:57:44] vrb: Tgstation.Server.Host.Components.Deployment.DmbFactory (Instance:1|Job:|Request:GET /DreamDaemon|User:1|Monitor:|Bridge:|Chat:|IR:bce3b14d-06a6-48bc-8f42-4a9dee355629)
    Compile job 1 lock count now: 3
[18:57:46] dbg: Tgstation.Server.Host.Controllers.JobController (Instance:1|Job:|Request:GET /Job|User:1|Monitor:|Bridge:|Chat:|IR:)
    Starting API request: Version: 8.1.1. User-Agent: tgstation-server-control-panel/2.0.1
[18:57:46] dbg: Tgstation.Server.Host.Controllers.JobController (Instance:1|Job:|Request:GET /Job/4|User:1|Monitor:|Bridge:|Chat:|IR:)
    Starting API request: Version: 8.1.1. User-Agent: tgstation-server-control-panel/2.0.1
[18:57:46] dbg: Tgstation.Server.Host.Controllers.JobController (Instance:1|Job:|Request:GET /Job/5|User:1|Monitor:|Bridge:|Chat:|IR:)
    Starting API request: Version: 8.1.1. User-Agent: tgstation-server-control-panel/2.0.1
```

**Comment by alexkar598** [comment]
Issue was fixed at some point and besides, manually polling the jobs has been removed now that the TGS api returns progress in the List endpoint
